name: navifit_1
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  appwrite: ^11.0.1
  get: ^4.6.5
  get_storage: ^2.0.3
  flutter_svg: ^2.0.10
  google_fonts: ^5.0.0
  flutter_screenutil: ^5.0.0+2
  geolocator: ^14.0.0
  geocoding: ^2.0.0
  google_maps_flutter: ^2.2.0
  flutter_map: ^6.1.0
  flutter_map_cancellable_tile_provider: ^1.0.0
  latlong2: ^0.9.1
  # ❌ Eliminado para evitar conflicto
  # flutter_web_auth_2: ^4.1.0  ❌
  # ✅ Appwrite ya trae una versión compatible (2.x), no agregues manualmente

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.0
  flutter_localizations:
    sdk: flutter
  flutter_lints: ^5.0.0
  rename: ^3.0.1

flutter:
  uses-material-design: true
